FROM ubuntu:18.04

RUN apt-get update
RUN apr-get upgrade
RUN apt-get install -y \
	vim \
	git \
	wget \
	valgrind \
	clang \
	make \
	unzip

RUN apt-get install -y \
	php \
	php-cgi \
	php-mysql

ADD	https://wordpress.org/latest.tar.gz /var/www/html/


